name: PHP CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 1'

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup PHP
        uses: shivammathur/setup-php@86e1ccdd8ddc47bffc29bf667143f363a4cdfdbc
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
    
      - name: Composer install
        run: composer install
    
      - name: PHP Linting
        run: ./vendor/bin/phpcs --standard=.duo_linting.xml -n src/* tests

      - name: PHP tests
        run: ./vendor/bin/phpunit --process-isolation tests
